
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COLON COMMA COUT DOUBLECOLON ERROR GT HASH ID INCLUDE INT IOSTREAM LBRACE LPAREN LT MAIN NUMBER PLUS RBRACE RETURN RPAREN SEMI STD STRINGincludes : HASH INCLUDE LT IOSTREAM GT INT MAIN LPAREN RPAREN LBRACE STD DOUBLECOLON COUT LT LT STRING SEMI RETURN NUMBER SEMI RBRACE'
    
_lr_action_items = {'HASH':([0,],[2,]),'$end':([1,22,],[0,-1,]),'INCLUDE':([2,],[3,]),'LT':([3,14,15,],[4,15,16,]),'IOSTREAM':([4,],[5,]),'GT':([5,],[6,]),'INT':([6,],[7,]),'MAIN':([7,],[8,]),'LPAREN':([8,],[9,]),'RPAREN':([9,],[10,]),'LBRACE':([10,],[11,]),'STD':([11,],[12,]),'DOUBLECOLON':([12,],[13,]),'COUT':([13,],[14,]),'STRING':([16,],[17,]),'SEMI':([17,20,],[18,21,]),'RETURN':([18,],[19,]),'NUMBER':([19,],[20,]),'RBRACE':([21,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'includes':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> includes","S'",1,None,None,None),
  ('includes -> HASH INCLUDE LT IOSTREAM GT INT MAIN LPAREN RPAREN LBRACE STD DOUBLECOLON COUT LT LT STRING SEMI RETURN NUMBER SEMI RBRACE','includes',21,'p_includes','app2.py',66),
]
